---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
stages:
  Acceptance:
    npmExecuteEndToEndTests: false
    cloudFoundryDeploy: false
  Release:
    tmsExport: false
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "31d6b40ftrial"
    cfSpace: "dev"
    cfCredentialsId: "btp"
    deployType: "standard"
    cloudFoundryDeploy: true
  Build:
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Malware Scan:
    malwareExecuteScan: true
  Compliance:
    sonarExecuteScan: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  npmExecuteLint:
    failOnError: true
